#!/usr/bin/env bash

BOOK=$(fd -t f -E "*zip" . ~/Documents/Books/ | dmenu -l 5 -p "Books")

if file "$BOOK" | grep -q text$; then
    alacritty -e nvim -c "Goyo" -c "set nornu nonu" "$BOOK"
elif file "$BOOK" | grep -q -i pdf; then
    zathura "$BOOK"
fi
