#!/bin/sh

# Simple script that uses maim to take a screenshot
# It adds shadow to the screenshots using imagemagick

# Use the date and time for the output file
output=$HOME/Pictures/screenshots/"$(date +%s_%h%d_%H:%M:%S).png"

# Prompt user for how to take screenshot
OPT=$(cat <<EOF | dmenu -l 3 -p "Maim"
active
select
full
EOF
)

case "$OPT" in
    "active") maim -i $(xdotool getactivewindow) | \
        convert - \( +clone -background black -shadow 80x20+0+15 \) \
        +swap -background none -layers merge +repage "$output" || exit;;
    "select") maim -s | \
        convert - \( +clone -background black -shadow 80x20+0+15 \) \
        +swap -background none -layers merge +repage "$output" || exit;;
    "full") maim | \
        convert - \( +clone -background black -shadow 80x20+0+15 \) \
        +swap -background none -layers merge +repage "$output" || exit;;
    "") exit ;;
esac

# Notify user that screenshot has been taken successfully
notify-send "Maim" "Screenshot Taken"
