#!/usr/bin/sh

# Generating Sprites with ImageMagick and awk
# ref: https://www.omarpolo.com/post/css-sprites-awk-imagemagick.html

# convert "$1" -append "$2.png" # append vertically
# convert "$1" +append "$2.png" # append horizontally

#!/bin/sh

convert sprites/* -append img/sprites.png # vertically

for i in sprites/*; do
    identify -format '%W %H %f\n' $i
done | awk '
function fname(path) {
    sub (".png", "", path)
    return path
}

BEGIN {
    y = 0

    print "%sprite-base {"
    print " background-image: url(/img/sprites.png);"
    print " background-repeat: no-repeat;"
    print "}"
    print ""
}

{
    width = $1
    height = $2
    class = fname($3)

    print "%sprite-" class " {"
    print " @extend %sprite-base;"
    if (y == 0)
        print " background-position: 0 0;"
    else
        print " background-position: 0 -" y "px;"
    print "}"
    print ""

    y += height;
}
' > scss/_sprites.scss
