#!/usr/bin/env bash

# This script enables you to see the definition of the words under the cursor
# using the terminal based dictionary utility, sdcv.

# prerequisite: xclip, sdcv

sdcv -n --utf8-output "$(xclip -o -sel clip)" 2>&1
echo "$(xclip -o -sel clip)" >> ~/.words

# vim: ft=sh
