#!/bin/sh

VPN=$(cat <<EOF | dmenu -p "ProtonVPN"
connect
disconnect
EOF
)

if [ $VPN = "connect" ]; then
    notify-send "ProtonVPN" "Connecting..."
    sudo protonvpn c -f >/dev/null 2>&1 && notify-send "ProtonVPN" "You are now connected"
elif [ $VPN = "disconnect" ]; then
    notify-send "ProtonVPN" "Disconnecting..."
    sudo protonvpn d >/dev/null 2>&1 && notify-send "ProtonVPN" "You are now Disconnected"
fi
